pipeline {
    agent none

    stages {
        stage('Install RKE2 on Master Node 1') {
            agent { label 'masternode1-agent' } // Specify the label for the Jenkins master node
            steps {
                sh 'chmod +x ./rancher/install_rke2_master.sh'
                sh './rancher/install_rke2_master.sh'
            }
        }

        stage('Verify Installation on Master Node 1') {
            agent { label 'masternode-agent' } // Specify the label for the Jenkins master node
            steps {
                script {
                    // Verify RKE2 installation (e.g., kubectl version or other checks)
                    sh 'kubectl version'
                }
            }
        }

        stage('Install RKE2 on Worker Node 1') {
            agent { label 'workernode1-agent' } // Specify the label for the worker node 1
            steps {
                sh 'chmod +x ./rancher/install_rke2_worker1.sh'
                sh './rancher/install_rke2_worker1.sh'
            }
        }

        stage('Verify Installation on Worker Node 1') {
            agent { label 'workernode1-agent' } // Specify the label for worker node 1
            steps {
                script {
                    // Verify RKE2 installation (e.g., kubectl version or other checks)
                    sh 'kubectl version'
                }
            }
        }

        stage('Install RKE2 on Worker Node 2') {
            agent { label 'workernode2-agent' } // Specify the label for worker node 2
            steps {
                sh 'chmod +x ./rancher/install_rke2_worker2.sh'
                sh './rancher/install_rke2_worker2.sh'
            }
        }

        stage('Verify Installation on Worker Node 2') {
            agent { label 'workernode2-agent' } // Specify the label for worker node 2
            steps {
                script {
                    // Verify RKE2 installation (e.g., kubectl version or other checks)
                    sh 'kubectl version'
                }
            }
        }
    }     
                    
    post {
        success {
            echo 'RKE2 installation and verification succeeded!'
        }
        failure {
            echo 'RKE2 installation or verification failed!'
        }
    }
}
