apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-rules
data:
  alerting-rules.yaml: |
    # Your alerting rules YAML content here
    # Example:
    - name: "HighErrorRate"
      rules:
      - alert: "HighErrorRateAlert"
        expr: "job:request_error_rate{job=\"example-service\"} > 0.5"
        for: "5m"
        labels:
          severity: "critical"
        annotations:
          summary: "High error rate detected"
          description: "The error rate is above 0.5 for 5 minutes."
